export const communes = [
  // Province d'Agadir Ida-Outanane
  "Agadir",
  "Ait Melloul",
  "Drarga",
  "Aourir",
  "Taghazout",
  "Tamri",
  "Amskroud",
  "Imouzzer Ida Outanane",
  "Imsouane",
  "Temsia",
  "Aqesri",
  "Aziar",
  "Idmine",
  "Tadrart",
  "Tikiouine",
  "Tlata Taghazout",

  // Province d'Inezgane-Ait Melloul
  "Inezgane",
  "Dcheira El Jihadia",
  "Lqliaa",
  "Oulad Teima",
  "Biougra",
  "Ait Amira",
  "Ait Mzal",
  "El Guerdane",
  "Oulad Dahou",
  "Oulad Zidane",
  "Sidi Bibi",
  "Sidi Boulbra",
  "Sidi Mzal",
  "Temsia",
  "Tnine Chtouka",

  // Province de Chtouka-Ait Baha
  "Biougra",
  "Ait Amira",
  "Ait Mzal",
  "El Guerdane",
  "Oulad Dahou",
  "Oulad Zidane",
  "Sidi Bibi",
  "Sidi Boulbra",
  "Sidi Mzal",
  "Temsia",
  "Tnine Chtouka",

  // Province de Taroudant
  "Taroudant",
  "Aoulouz",
  "El Kelaâ des Sraghna",
  "Irherm",
  "Oulad Berhil",
  "Oulad Teima",
  "Taliouine",
  "Tata",
  "Tiznit",
  "Ait Iaaza",
  "Ait Mzal",
  "Amalou",
  "Ida Ougnidif",
  "Sidi Ahmed Ou Abdellah",
  "Sidi Borja",
  "Sidi Mzal",
  "Tafingoult",
  "Tassousfi",
  "Tizgzaouine",
  "Toufelaazt",

  // Province de Tiznit
  "Tiznit",
  "Anzi",
  "Arbaa Ait Ahmed",
  "Sidi Ifni",
  "Tafraout",
  "Tiznit",
  "Ait Ouafqa",
  "Arbaa Rasmouka",
  "Bounaamane",
  "El Maader El Kabir",
  "Reggada",
  "Sidi Ahmed Ou Moussa",
  "Sidi Bouabdelli",
  "Tnine Amellou",
  "Tnine Sidi Lyamani",

  // Province de Tata
  "Tata",
  "Akka",
  "Fam El Hisn",
  "Foum Zguid",
  "Tissint",
  "Ait Oubelli",
  "Kasbat Sidi Abdellah",
  "Oum El Guerdane",
  "Tamanart",
  "Tizounine",

] as const;

export type Commune = typeof communes[number]; 