export const communes = [
  // Province d'Agadir Ida-Outanane
  "Agadir",
  "Ait Melloul",
  "Drarga",
  "Aourir",
  "Taghazout",
  "Tamri",
  "Amskroud",
  "Imouzzer",
  "Imsouane",
  "Aqesri",
  "Aziar",
  "Idmine",
  "Tadrart",

  // Province d'Inezgane-Ait Melloul
  "Inezgane",
  "Dcheira El Jihadia",
  "Lqliaa",
  "Temsia",
  "Oulad Dahou",

  // Province de Chtouka-Ait Baha
  "Biougra",
  "Ait Baha",
  "Ait Amira",
  "Ait Mzal",
  "Ait Ouadrim",
  "Ait Milk",
  "Belfaa",
  "Inchaden",
  "Massa",
  "Aouguenz",
  "Sidi Bibi",
  "Sidi Abdallah El Bouchouari",
  "Ida Ougnidif",
  "Hilala",
  "Sidi Ouassay",
  "Imi Mqourn",
  "Ouad Essafa",
  "Sidi Boushab",
  "Tanalt",
  "Targua Ntouchka",
  "Tassegdelt",
  "Tizi Ntakoucht",


  // Province de Taroudant
  "Taroudant",
  "Aoulouz",
  "Igherm",
  "Oulad Berhil",
  "Oulad Teima",
  "El Guerdane",
  "Taliouine",
  "Ait Iaaza",
  "Sidi Ahmed Ou Abdellah",
  "Sidi Borja",
  "Tassousfi",
  "Tizgzaouine",
  "Adar",
  "Ait Abdallah",
  "Amalou",
  "Azaghar N'Irs",
  "Imaouen",
  "Imi N'Tayart",
  "Nihit",
  "Oualqadi",
  "Sidi Boaal",
  "Sidi Mzal",
  "Tabia",
  "Tataoute",
  "Tindine",
  "Tisfane",
  "Toufelaazt",
  "Toumliline",
  "Arazane",
  "El Faid",
  "Ida Ou Gailal",
  "Ida Ougoummad",
  "Igli",
  "Igoudar Mnabha",
  "Lamhara",
  "Oulad Aissa",
  "Ouneine",
  "Sidi Abdellah Ou Said",
  "Sidi Ouaaziz",
  "Tafingoult",
  "Talgjount",
  "Tigouga",
  "Tinzart",
  "Tizi N'Test",
  "Toughmart",
  "Ahl Ramel",
  "Argana",
  "Assads",
  "Bigoudine",
  "Eddir",
  "El Koudia El Beida",
  "Imilmaiss",
  "Issen",
  "Lagfifat",
  "Lakhnafif",
  "Lamhadi",
  "Machraa El Ain",
  "Sidi Ahmed Ou Amar",
  "Sidi Boumoussa",
  "Sidi Moussa Lhamri",
  "Talmakante",
  "Tidsi Nissendalene",
  "Agadir Melloul",
  "Ahl Tifnoute",
  "Askaouen",
  "Assaisse",
  "Assaki",
  "Azrar",
  "Iguidi",
  "Sidi Hsaine",
  "Taouyalte",
  "Toubkal",
  "Zagmouzen",
  "Ouzioua",
  "Tisrasse",
  "Ahmar Laglalcha",
  "Ait Igas",
  "Ait Makhlouf",
  "Bounrar",
  "Freija",
  "Ida Ou Moumen",
  "Imoulass",
  "Lamnizla",
  "Sidi Dahmane",
  "Tafraouten",
  "Tamaloukte",
  "Tazemmourt",
  "Tiout",
  "Zaouia Sidi Tahar",


  // Province de Tiznit
  "Tiznit",
  "Anzi",
  "Arbaa Sahel",
  "Bounaamane",
  "El Maader El Kabir",
  "Ouijjane",
  "Sidi Bouabdelli",
  "Tnine Aglou",
  "Ait Issafen",
  "Arbaa Ait Ahmed",
  "Tafraout",
  "Ait Ouafqa",
  "Arbaa Rasmouka",
  "Reggada",
  "Sidi Ahmed Ou Moussa",
  "Ida Ou Gougmar",
  "Tafraout El Mouloud",
  "Tighmi",
  "Tizoughrane",
  "Tnine Aday",
  "Afella Ighir",
  "Ammelne",
  "Irigh N'Tahala",
  "Tarsouat",
  "Tassrirt",
  

  // Province de Tata
  "Tata",
  "Akka",
  "Fam El Hisn",
  "Foum Zguid",
  "Ait Ouabelli",
  "Kasbat Sidi Abdellah Ben Mbark",
  "Oum El Guerdane",
  "Tamanart",
  "Aguinane",
  "Akka Ighane",
  "Allougoum",
  "Ibn Yacoub",
  "Tissint",
  "Issafen",
  "Tagmout",
  "Tigzmerte",
  "Tizounine",
] as const;

export type Commune = typeof communes[number]; 